Feature: Flujo completo de registro de 7 usuarios de forma manual
    Como un usuario
    Quiero agregar los documentos de un prospecto
    Para finalizar el registro de forma satisfecha

  Background:
    Given el usuario está en la pantalla principal

  @buscar-usuarios-y-registrar-sci-basica
  Scenario Outline: Buscar usuario y registrar sci
    When buscar a: "<prospecto>"
    Then seleccionar al usuario del listado de la busqueda realizada
    Then seleccionar solicitud individual
    Then comienzo con la captura de datos complementarios de la prospecta "<estado_civil_soltera>" "<escolaridad>"
    Then captura datos domicilio antiguedad
    Then acreditacion del domicilio INE:"<ine>" parentesco:"<parentesco>"
    Then captura de datos familiar "<nombre_familiar>" "<tel_familiar>" "<caracteristicas_vivienda>" "<referencia_ubicacion>"
    Then captura datos actividad economica "<direccion_del_negocio>" "<ganancia_semanal>" "<otros_ingresos>" "<monto_pago_semanal>"
    Then captura datos referencia uno "<nombre_referencia>" "<tel_referencia_celular>"
    Then captura datos referencia dos "<nombre_referencia2>" "<tel_referencia_celular2>"
    Then captura datos crediticios "<monto_credito>" "<origen_recursos_credito>" "<destino_recursos_credito>"
    Then Volver al inicio con scroll

    # Examples:
    #   | prospecto  | estado_civil_soltera | escolaridad | ine | parentesco | nombre_familiar | tel_familiar | caracteristicas_vivienda | referencia_ubicacion | direccion_del_negocio | ganancia_semanal | otros_ingresos | monto_pago_semanal | nombre_referencia | tel_referencia_celular | nombre_referencia2 | tel_referencia_celular2 | monto_credito | origen_recursos_credito | destino_recursos_credito        |


      # | ARMITA    |SOLTERA |  SECUNDARIA  | SI  | PROPIO     | KAL             |   5229886350 | FACHADA PIEDRA VOLCANICA | FRENTE A PARQUE      | SAN JOSE              |             4008 |           2508 |               1500 | PANCRACIA         |             5525820280 | KARlI              |              5513195060 |          6000 | NEGOCIO FAMILIAR        | CRECIMIENTO DE NEGOCIO FAMILIAR |
      # | BEBA      |SOLTERA |  SECUNDARIA  | SI  | PROPIO     | KAL             |   5229886351 | FACHADA PIEDRA VOLCANICA | FRENTE A PARQUE      | SAN JOSE              |             4008 |           2508 |               1500 | PANCRACIA         |             5525820281 | KARlI              |              5513195061 |          6000 | NEGOCIO FAMILIAR        | CRECIMIENTO DE NEGOCIO FAMILIAR |
      # | CAMILA    |SOLTERA |  SECUNDARIA  | SI  | PROPIO     | KAL             |   5229886352 | FACHADA PIEDRA VOLCANICA | FRENTE A PARQUE      | SAN JOSE              |             4008 |           2508 |               1500 | PANCRACIA         |             5525820282 | KARlI              |              5513195062 |          6000 | NEGOCIO FAMILIAR        | CRECIMIENTO DE NEGOCIO FAMILIAR |


      # | PNTITLAN    | SOLTERA |  SECUNDARIA  | SI  | PROPIO     | KAL             |   5229886350 | FACHADA PIEDRA VOLCANICA | FRENTE A PARQUE      | SAN JOSE              |             4008 |           2508 |               1500 | PANCRACIA         |             5525820280 | KARlI              |              5513195060 |          6000 | NEGOCIO FAMILIAR        | CRECIMIENTO DE NEGOCIO FAMILIAR |
      # | LEOBARDO    | SOLTERA |  SECUNDARIA  | SI  | PROPIO     | KAL             |   5229886351 | FACHADA PIEDRA VOLCANICA | FRENTE A PARQUE      | SAN JOSE              |             4008 |           2508 |               1500 | PANCRACIA         |             5525820281 | KARlI              |              5513195061 |          6000 | NEGOCIO FAMILIAR        | CRECIMIENTO DE NEGOCIO FAMILIAR |
      # | MATIAS      | SOLTERA |  SECUNDARIA  | SI  | PROPIO     | KAL             |   5229886352 | FACHADA PIEDRA VOLCANICA | FRENTE A PARQUE      | SAN JOSE              |             4008 |           2508 |               1500 | PANCRACIA         |             5525820282 | KARlI              |              5513195062 |          6000 | NEGOCIO FAMILIAR        | CRECIMIENTO DE NEGOCIO FAMILIAR |
      # | VULKANO     | SOLTERA |  SECUNDARIA  | SI  | PROPIO     | KAL             |   5229886353 | FACHADA PIEDRA VOLCANICA | FRENTE A PARQUE      | SAN JOSE              |             4008 |           2508 |               1500 | PANCRACIA         |             5525820283 | KARlI              |              5513195063 |          6000 | NEGOCIO FAMILIAR        | CRECIMIENTO DE NEGOCIO FAMILIAR |
      # | CARLOS      | SOLTERA |  SECUNDARIA  | SI  | PROPIO     | KAL             |   5229886354 | FACHADA PIEDRA VOLCANICA | FRENTE A PARQUE      | SAN JOSE              |             4008 |           2508 |               1500 | PANCRACIA         |             5525820284 | KARlI              |              5513195064 |          6000 | NEGOCIO FAMILIAR        | CRECIMIENTO DE NEGOCIO FAMILIAR |
      # | GUADALUPANO | SOLTERA |  SECUNDARIA  | SI  | PROPIO     | KAL             |   5229886355 | FACHADA PIEDRA VOLCANICA | FRENTE A PARQUE      | SAN JOSE              |             4008 |           2508 |               1500 | PANCRACIA         |             5525820285 | KARlI              |              5513195065 |          6000 | NEGOCIO FAMILIAR        | CRECIMIENTO DE NEGOCIO FAMILIAR |



      # | EVELARDO | SOLTERA |  SECUNDARIA  | SI  | PROPIO     | KAL             |   5229886354 | FACHADA PIEDRA VOLCANICA | FRENTE A PARQUE      | SAN JOSE              |             4008 |           2508 |               1500 | pANCRACIA         |             5525820284 | KARlI              |              5513195074 |          6000 | NEGOCIO FAMILIAR        | CRECIMIENTO DE NEGOCIO FAMILIAR |
      # | LIAM     | soltera |  secundaria  | si  | Propio     | Kal             |   5229886354 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820284 | KarLI              |              5513195074 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | OISIN    | soltera |  secundaria  | si  | Propio     | Kal             |   5229886355 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820285 | KarLI              |              5513195075 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | RORY     | soltera |  secundaria  | si  | Propio     | Kal             |   5229886351 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820281 | KarLI              |              5513195071 |          6000 | negocio familiar        | crecimiento de negocio familiar |


      # | APOLONIA   | soltera |  secundaria  | si  | Propio     | Kal             |   5229886354 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820284 | KarLI              |              5513195074 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | BULMARA    | soltera |  secundaria  | si  | Propio     | Kal             |   5229886355 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820285 | KarLI              |              5513195075 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | CIFORA     | soltera |  secundaria  | si  | Propio     | Kal             |   5229886351 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820281 | KarLI              |              5513195071 |          6000 | negocio familiar        | crecimiento de negocio familiar |

      
      # | APOLONIA |soltera              | secundaria  | si  | Propio     | Kal             |   5229886354 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820284 | KarLI              |              5513195074 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | BULMARA  |soltera              | secundaria  | si  | Propio     | Kal             |   5229886355 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820285 | KarLI              |              5513195075 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | CIFORA   |soltera              | secundaria  | si  | Propio     | Kal             |   5229886351 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820281 | KarLI              |              5513195071 |          6000 | negocio familiar        | crecimiento de negocio familiar |

      # | EVELARDA   |soltera              | secundaria  | si  | Propio     | Kal             |   5229886354 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820284 | KarLI              |              5513195074 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | FREMIDA    |soltera              | secundaria  | si  | Propio     | Kal             |   5229886355 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820285 | KarLI              |              5513195075 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | GUSABIA    |soltera              | secundaria  | si  | Propio     | Kal             |   5229886351 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820281 | KarLI              |              5513195071 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | FREMIDA    |soltera              | secundaria  | si  | Propio     | Kal             |   5229886351 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820281 | KarLI              |              5513195071 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | GUSABIA    |soltera              | secundaria  | si  | Propio     | Kal             |   5229886351 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820281 | KarLI              |              5513195071 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | HILARIA    |soltera              | secundaria  | si  | Propio     | Kal             |   5229886352 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820282 | KarLI              |              5513195072 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | BULMARA  | soltera              | secundaria  | si  | Propio     | Kal             |   5229886353 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820283 | KarLI              |              5513195073 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | CIFORA   | soltera              | secundaria  | si  | Propio     | Kal             |   5229886354 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820284 | KarLI              |              5513195074 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | DOROTEA  | soltera              | secundaria  | si  | Propio     | Kal             |   5229886352 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820282 | KarLI              |              5513195072 |          6000 | negocio familiar        | crecimiento de negocio familiar |

      # | DOROTEA    |soltera              | secundaria  | si  | Propio     | Kal             |   5229886353 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820283 | KarLI              |              5513195073 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      
      
      # | HILARIA    |soltera              | secundaria  | si  | Propio     | Kal             |   5229886351 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820281 | KarLI              |              5513195071 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | INDONECIA  |soltera              | secundaria  | si  | Propio     | Kal             |   5229886351 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820281 | KarLI              |              5513195071 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | JEREMIOS   |soltera              | secundaria  | si  | Propio     | Kal             |   5229886352 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820282 | KarLI              |              5513195072 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | KAZAMIA    |soltera              | secundaria  | si  | Propio     | Kal             |   5229886350 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820280 | KarLI              |              5513195070 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | LORETANA   |soltera              | secundaria  | si  | Propio     | Kal             |   5229886351 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820281 | KarLI              |              5513195071 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | MONIQUILLA |soltera              | secundaria  | si  | Propio     | Kal             |   5229886352 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820282 | KarLI              |              5513195072 |          6000 | negocio familiar        | crecimiento de negocio familiar |

      # | NIONDIDA   |soltera              | secundaria  | si  | Propio     | Kal             |   5229886350 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820280 | KarLI              |              5513195070 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | OPOLINA    |soltera              | secundaria  | si  | Propio     | Kal             |   5229886351 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820281 | KarLI              |              5513195071 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | PULPANA    |soltera              | secundaria  | si  | Propio     | Kal             |   5229886352 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820282 | KarLI              |              5513195072 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | QUESADIRIA |soltera              | secundaria  | si  | Propio     | Kal             |   5229886350 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820280 | KarLI              |              5513195070 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | RAMONA     |soltera              | secundaria  | si  | Propio     | Kal             |   5229886352 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820282 | KarLI              |              5513195072 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | SAMILA     |soltera              | secundaria  | si  | Propio     | Kal             |   5229886353 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820283 | KarLI              |              5513195073 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | TRIGULA    |soltera              | secundaria  | si  | Propio     | Kal             |   5229886354 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820284 | KarLI              |              5513195074 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | ULARIA     |soltera              | secundaria  | si  | Propio     | Kal             |   5229886355 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820285 | KarLI              |              5513195075 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | VIVIANA    |soltera              | secundaria  | si  | Propio     | Kal             |   5229886350 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820280 | KarLI              |              5513195070 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | XINA       |soltera              | secundaria  | si  | Propio     | Kal             |   5229886351 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820281 | KarLI              |              5513195071 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | YADIRA     |soltera              | secundaria  | si  | Propio     | Kal             |   5229886352 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820282 | KarLI              |              5513195072 |          6000 | negocio familiar        | crecimiento de negocio familiar |
 # | JAKATULIA |     soltera              | secundaria  | si  | Propio     | Kal             |   5229886352 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820282 | KarLI              |              5513195072 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | YOYIS     |soltera              | secundaria  | si  | Propio     | Kal             |   5229886353 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820283 | KarLI              |              5513195073 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | MIRANDA   |soltera              | secundaria  | si  | Propio     | Kal             |   5229886354 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820284 | KarLI              |              5513195074 |          6000 | negocio familiar        | crecimiento de negocio familiar |
# | FILIBERTA |
# | REGANA    |
# | HADANIS   |
# | UMILDADA  |
# | OTRILLA   |
# | GENEBRAS  |
      # | DAFNE    |soltera              | secundaria  | si  | Propio     | Kal             |   5229886353 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820283 | KarLI              |              5513195073 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | FIONA    |soltera              | secundaria  | si  | Propio     | Kal             |   5229886354 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820284 | KarLI              |              5513195074 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | EIR      |soltera              | secundaria  | si  | Propio     | Kal             |   5229886355 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820285 | KarLI              |              5513195075 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | HADA     |soltera              | secundaria  | si  | Propio     | Kal             |   5229886351 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820281 | KarLI              |              5513195071 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | TEA      |soltera              | secundaria  | si  | Propio     | Kal             |   5229886351 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820281 | KarLI              |              5513195071 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | OFELIA   |soltera              | secundaria  | si  | Propio     | Kal             |   5229886351 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820281 | KarLI              |              5513195071 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | GINEBRA  |soltera              | secundaria  | si  | Propio     | Kal             |   5229886352 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820282 | KarLI              |              5513195072 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | JARINTIA |soltera              | secundaria  | si  | Propio     | Kal             |   5229886350 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820280 | KarLI              |              5513195070 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | HABIBAH           | soltera              | secundaria  | si  | Propio     | Kal             |   5229886352 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820282 | KarLI              |              5513195072 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | ESPERANZA         | soltera              | secundaria  | si  | Propio     | Kal             |   5229886353 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820283 | KarLI              |              5513195073 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | LEMURY            | soltera              | secundaria  | si  | Propio     | Kal             |   5229886354 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820284 | KarLI              |              5513195074 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | UMELDA            | soltera              | secundaria  | si  | Propio     | Kal             |   5229886355 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820285 | KarLI              |              5513195075 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | PNTITLAN          | soltera              | secundaria  | si  | Propio     | Kal             |   5229886351 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820281 | KarLI              |              5513195071 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | PNTITLAN          | soltera              | secundaria  | si  | Propio     | Kal             |   5229886351 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820281 | KarLI              |              5513195071 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | LEOBARDO          | soltera              | secundaria  | si  | Propio     | Kal             |   5229886351 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820281 | KarLI              |              5513195071 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | MATIAS            | soltera              | secundaria  | si  | Propio     | Kal             |   5229886352 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820282 | KarLI              |              5513195072 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | VULKANO           | soltera              | secundaria  | si  | Propio     | Kal             |   5229886350 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820280 | KarLI              |              5513195070 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | MORTANDAD         | soltera              | secundaria  | si  | Propio     | Kal             |   5229886351 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820281 | KarLI              |              5513195071 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | BRAZILIA          | soltera              | secundaria  | si  | Propio     | Kal             |   5229886352 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820282 | KarLI              |              5513195072 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | YADIRA            | soltera              | secundaria  | si  | Propio     | Kal             |   5229886350 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820280 | KarLI              |              5513195070 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | CARLOS            | soltera              | secundaria  | si  | Propio     | Kal             |   5229886351 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820281 | KarLI              |              5513195071 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | GUADALUPANO       | soltera              | secundaria  | si  | Propio     | Kal             |   5229886352 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820282 | KarLI              |              5513195072 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | CASIMIRO          | soltera              | secundaria  | si  | Propio     | Kal             |   5229886350 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820280 | KarLI              |              5513195070 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | MIRANDA           | soltera              | secundaria  | si  | Propio     | Kal             |   5229886352 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820282 | KarLI              |              5513195072 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | JACABRIA          | soltera              | secundaria  | si  | Propio     | Kal             |   5229886353 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820283 | KarLI              |              5513195073 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | CRIPTONIANA       | soltera              | secundaria  | si  | Propio     | Kal             |   5229886354 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820284 | KarLI              |              5513195074 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | PAMELOTA          | soltera              | secundaria  | si  | Propio     | Kal             |   5229886355 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820285 | KarLI              |              5513195075 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | ULTRANA           | soltera              | secundaria  | si  | Propio     | Kal             |   5229886350 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820280 | KarLI              |              5513195070 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | GAMALIELA         | soltera              | secundaria  | si  | Propio     | Kal             |   5229886351 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820281 | KarLI              |              5513195071 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | KARIAN            | soltera              | secundaria  | si  | Propio     | Kal             |   5229886352 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820282 | KarLI              |              5513195072 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | LORETIANA         | soltera              | secundaria  | si  | Propio     | Kal             |   5229886350 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820280 | KarLI              |              5513195070 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | Diana Isabel      | soltera              | secundaria  | si  | Propio     | Kal             |   5229886350 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5521404090 | KarLI              |              5503112660 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | Gabriela Fernanda | soltera              | secundaria  | si  | Propio     | Kal             |   5229886350 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820280 | KarLI              |              5513195070 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | Monica Alejandra  | soltera              | secundaria  | si  | Propio     | Kal             |   5229886351 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820281 | KarLI              |              5513195071 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | Sofia Mariana     | soltera              | secundaria  | si  | Propio     | Kal             |   5229886350 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5521404090 | KarLI              |              5503112660 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | DENISS            | soltera              | secundaria  | si  | Propio     | Kal             |   5229886352 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820282 | KarLI              |              5513195072 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | EMILIA            | soltera              | secundaria  | si  | Propio     | Kal             |   5229886353 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820283 | KarLI              |              5513195073 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | FERNANDA          | soltera              | secundaria  | si  | Propio     | Kal             |   5229886354 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820284 | KarLI              |              5513195074 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | GUADALUPE         | soltera              | secundaria  | si  | Propio     | Kal             |   5229886355 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820285 | KarLI              |              5513195075 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | HORACIA           | soltera              | secundaria  | si  | Propio     | Kal             |   5229886350 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820280 | KarLI              |              5513195070 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | IMELDA            | soltera              | secundaria  | si  | Propio     | Kal             |   5229886351 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820281 | KarLI              |              5513195071 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | JAZMIN            | soltera              | secundaria  | si  | Propio     | Kal             |   5229886352 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820282 | KarLI              |              5513195072 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | KAREN             | soltera              | secundaria  | si  | Propio     | Kal             |   5229886350 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820280 | KarLI              |              5513195070 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | laURA             | soltera              | secundaria  | si  | Propio     | Kal             |   5229886351 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820281 | KarLI              |              5513195071 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | MONICA            | soltera              | secundaria  | si  | Propio     | Kal             |   5229886352 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820282 | KarLI              |              5513195072 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | NADIA             | soltera              | secundaria  | si  | Propio     | Kal             |   5229886353 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820283 | KarLI              |              5513195073 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | OSCARINA          | soltera              | secundaria  | si  | Propio     | Kal             |   5229886354 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820284 | KarLI              |              5513195074 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | PETRONILA         | soltera              | secundaria  | si  | Propio     | Kal             |   5229886355 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820285 | KarLI              |              5513195075 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | rocio             | soltera              | secundaria  | si  | Propio     | Kal             |   5229886350 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820280 | KarLI              |              5513195070 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | SABRINA           | soltera              | secundaria  | si  | Propio     | Kal             |   5229886351 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820281 | KarLI              |              5513195071 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | TARINKA           | soltera              | secundaria  | si  | Propio     | Kal             |   5229886352 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820282 | KarLI              |              5513195072 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | UVALDA            | soltera              | secundaria  | si  | Propio     | Kal             |   5229886355 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820285 | KarLI              |              5513195075 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | VICTORIA          | soltera              | secundaria  | si  | Propio     | Kal             |   5229886350 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820280 | KarLI              |              5513195070 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | XIMENA            | soltera              | secundaria  | si  | Propio     | Kal             |   5229886351 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820281 | KarLI              |              5513195071 |          6000 | negocio familiar        | crecimiento de negocio familiar |
      # | ZELDA             | soltera              | secundaria  | si  | Propio     | Kal             |   5229886352 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5525820282 | KarLI              |              5513195072 |          6000 | negocio familiar        | crecimiento de negocio familiar |


  @buscar-usuarios-y-registrar-sci-1
  Scenario Outline: Buscar usuario y registrar sci
    When buscar a: "<usuario>"
    Then seleccionar al usuario del listado de la busqueda realizada
    Then seleccionar solicitud individual
    Then captura datos domicilio antiguedad
    Then acreditacion del domicilio INE:"<ine>" parentesco:"<parentesco>"
    Then captura de datos familiar "<nombre_familiar>" "<tel_familiar>" "<caracteristicas_vivienda>" "<referencia_ubicacion>"
    Then captura datos actividad economica "<direccion_del_negocio>" "<ganancia_semanal>" "<otros_ingresos>" "<monto_pago_semanal>"
    Then captura datos referencia uno "<nombre_referencia>" "<tel_referencia_celular>"
    Then captura datos referencia dos "<nombre_referencia2>" "<tel_referencia_celular2>"
    Then captura datos crediticios "<monto_credito>" "<origen_recursos_credito>" "<destino_recursos_credito>"
    Then Volver al inicio con scroll

    Examples:
      | usuario | ine | parentesco | nombre_familiar | tel_familiar | caracteristicas_vivienda | referencia_ubicacion | direccion_del_negocio | ganancia_semanal | otros_ingresos | monto_pago_semanal | nombre_referencia | tel_referencia_celular | nombre_referencia2 | tel_referencia_celular2 | monto_credito | origen_recursos_credito | destino_recursos_credito        |
      | Ana     | si  | Propio     | Kal             |   5229886350 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5521404090 | KarLI              |              5503112660 |          6000 | negocio familiar        | crecimiento de negocio familiar |

  @buscar-usuarios-y-registrar-sci-2
  Scenario Outline: Buscar usuario y registrar sci
    When buscar a: "<usuario>"
    Then seleccionar al usuario del listado de la busqueda realizada
    Then seleccionar solicitud individual
    Then captura datos actividad economica "<direccion_del_negocio>" "<ganancia_semanal>" "<otros_ingresos>" "<monto_pago_semanal>"
    Then captura datos referencia uno "<nombre_referencia>" "<tel_referencia_celular>"
    Then captura datos referencia dos "<nombre_referencia2>" " "<tel_referencia_celular2>"
    Then captura datos crediticios "<monto_credito>" "<origen_recursos_credito>" "<destino_recursos_credito>"
    Then Volver al inicio con scroll

    Examples:
      | usuario | nombre_familiar | tel_familiar | caracteristicas_vivienda | referencia_ubicacion | direccion_del_negocio | ganancia_semanal | otros_ingresos | monto_pago_semanal | nombre_referencia | tel_referencia_celular | nombre_referencia2 | tel_referencia_celular2 | monto_credito | origen_recursos_credito | destino_recursos_credito        |
      | Ana     | Kal             |   5229886350 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5521404090 | KarLI              |              5503112660 |          6000 | negocio familiar        | crecimiento de negocio familiar |

  @buscar-usuarios-y-registrar-sci-3
  Scenario Outline: Buscar usuario y registrar sci
    When buscar a: "<usuario>"
    Then seleccionar al usuario del listado de la busqueda realizada
    Then seleccionar solicitud individual
    Then captura datos referencia uno "<nombre_referencia>" "<tel_referencia_celular>"
    Then captura datos referencia dos "<nombre_referencia2>" "<tel_referencia_celular2>"
    Then captura datos crediticios "<monto_credito>" "<origen_recursos_credito>" "<destino_recursos_credito>"
    Then Volver al inicio con scroll

    Examples:
      | usuario | nombre_familiar | tel_familiar | caracteristicas_vivienda | referencia_ubicacion | direccion_del_negocio | ganancia_semanal | otros_ingresos | monto_pago_semanal | nombre_referencia | tel_referencia_celular | nombre_referencia2 | tel_referencia_celular2 | monto_credito | origen_recursos_credito | destino_recursos_credito        |
      | Ana     | Kal             |   5229886350 | fachada piedra volcanica | frente a parque      | san jose              |             4008 |           2508 |               1500 | Pancracia         |             5521404090 | KarLI              |              5503112660 |          6000 | negocio familiar        | crecimiento de negocio familiar |

  @buscar-usuarios-y-registrar-sci-4
  Scenario Outline: Buscar usuario y registrar sci
    When buscar a: "<usuario>"
    Then seleccionar al usuario del listado de la busqueda realizada
    Then seleccionar solicitud individual
    Then captura datos crediticios "<monto_credito>" "<origen_recursos_credito>" "<destino_recursos_credito>"
    # Then Volver al inicio con scroll

    Examples:
      | usuario | monto_credito | origen_recursos_credito | destino_recursos_credito        |
      | Ana     |          6000 | negocio familiar        | crecimiento de negocio familiar |
