# Archivo: config.py
VAL_SECCION_TEXTO_CAPTURA_DATOS = "CAPTURA DATOS PERSONA"


#CONSULTA RAPIDA
PRE_APROBADO = "HA SIDO PRE APROB"
FELICIDADES = "¡FELICIDADES!"
NUEVA_CONULSTA = "NUEVA CONSULTA"
INFO_ADICIONAL = "VER INFORMACIÓN ADICIONAL"

#CONSULTA GRUPAL
VALIDACION_DUPLICIDAD_GRUPO = "nombre de grupo ingresado ya existe"

VALIDACION_CURP_LISTA_NEGRA = "Lo sentimos"
VALIDACION_CURP_LISTA_NEGRA_RAZON = "El CURP entra dentro del listado de palabras inconvenientes de renapo, favor de revisar"